version: '3.5'

services:
  api:
    build: .
    image: romainprignon/starter-api-ts:${TAG-latest}
    container_name: romainprignon_starter-api-ts
    command: npm run start:${ENV-prod}
    ports:
      - 4000
    external_links:
      - db
    volumes:
      - type: volume
        source: api
        target: /opt
    # deploy:
    #   replicas: 1
    #   restart_policy:
    #     condition: on-failure
    #     delay: 3s
    #     max_attempts: 3
    #   resources:
    #     limits:
    #       cpus: "0.25"
    #       memory: 500M

volumes:
  api:
