version: '3.5'

services:
  api:
    image: romainprignon/starter-api-ts:${API_TAG-0.4.0}
    container_name: romainprignon_starter-stack_api
    command: npm run start:local
    ports:
      - 4000:4000
    volumes:
      - .:/opt
    depends_on:
      - db
