version: '3.5'

services:
  api:
    image: romainprignon/starter-api-ts:latest
    container_name: starter-api-ts_api
    command: npm run start:local
    external_links:
      - db
    ports:
      - 4000:4000
    volumes:
      - .:/opt
